### ISSUE TITLE
Different licensing for the code

### ISSUE THREAD

**Issue by tupui** [rougier/scientific-visualization-book#12]
First of all, this looks amazing! 👏 

Would you consider making the code available using another license than a creative common?

The reason is that, as with StackOverflow, CC is not compatible with licenses like MIT and BSD.

**Comment by Arkelis** [comment]
Figures source code is licensed under BSD license according to the files headers (ex: https://github.com/rougier/scientific-visualization-book/blob/master/code/anatomy/anatomy.py)

**Comment by tupui** [comment]
I went this over too fast, thanks!
