### ISSUE TITLE
example code in Chapter 1,  Dimensions & resolution

### ISSUE THREAD

**Issue by mengliu1995** [rougier/scientific-visualization-book#15]
Excellent book! 
It may help to add "-verbose" in your example of using identify.

**Comment by rougier** [comment]
Thanks. For the `identify` command, you mean you do not get the same output without the `-verbose` option?

**Comment by xxyzz** [comment]
I installed ImageMagick 7.1.0 from Homebrew, the output without `-verbose` is just one line:

```
x.png PNG 512x512 512x512+0+0 8-bit sRGB 2288B 0.000u 0:00.003
```

I didn't know this issue exists when I created #21...

**Comment by rougier** [comment]
Thanks, it has been merged.
