### ISSUE TITLE
Typo - Page 28 in PDF

### ISSUE THREAD

**Issue by ncolton33** [rougier/scientific-visualization-book#17]
![typo](https://user-images.githubusercontent.com/26281702/142448362-923d2531-3d5c-4006-a17e-ce437bb83236.PNG)
Bottom of Page 28 in the PDF found here: https://hal.inria.fr/hal-03427242/document

The example code incorrectly displays 

`fig, ax = plt.subplots(figsize=(6,6),
subplot_kw={"aspect"=1})
`
it should read:
`fig, ax = plt.subplots(figsize=(6,6),
subplot_kw={"aspect":1})
`

**Comment by rougier** [comment]
Thanks, it has been corrected (in [anatomy.rst](https://github.com/rougier/scientific-visualization-book/blob/master/rst/anatomy.rst))
