### ISSUE TITLE
Reduce repetition in text (for example) in the anatomy chapter

### ISSUE THREAD

**Issue by kinow** [rougier/scientific-visualization-book#24]
Hello,

I found a typo in #23 , and next to it there are two "For example", one next to the other. I think we could reduce repetition by removing or replacing one of these two, but not sure what would be the best solution. Sorry.

Here's where it happens:

![image](https://user-images.githubusercontent.com/304786/143673182-3f8ed6c3-ea06-4859-94a8-fa2f55218abb.png)

Also, maybe it would be clearer to show in the former case that `GtkCairo` stands for `Gtk3` interface + `Cairo` renderer I think? Might be helpful to complete beginners.

Cheers
Bruno

**Comment by rougier** [comment]
Sorry for the delay and thanks for the comment. Maybe this can be replaced with `(e.g. GTK3Cairo that  stands for Gtk3 interface with Cairo renderer)`. Could you make a PR?

**Comment by kinow** [comment]
Not a problem. Sure, give a couple minutes and the PR should be ready. Thanks @rougier !
