### ISSUE TITLE
Transparency example (fig 12.1) not showing properly in pdf

### ISSUE THREAD

**Issue by RElbers** [rougier/scientific-visualization-book#29]
In figure 12.1 on page 149, the rightmost 3 markers are shown as white in the pdf. 
When I run the [script](https://github.com/rougier/scientific-visualization-book/blob/master/code/optimization/transparency.py) and save as .pdf the same happens, but when I save that figure as .png the markers are shades of grey (as expected).

Might just be a bug in matplotlib, since one would expect that saving as .pdf produces the same image as saving as .png. Besides the fact that one is vector based and the other is raster based.

**Comment by rougier** [comment]
Thansk for the report. It might be related to your PDF viewer. Can you check with another viewer?

**Comment by RElbers** [comment]
Same when opening in SumatraPDF, Firefox and Chrome.

**Comment by rougier** [comment]
OK. What is your OS?

**Comment by RElbers** [comment]
Hmm. The bug is present on my windows pc, but not when I boot up Ubuntu or on my macbook.
[This is what it looks like in Windows.](https://i.imgur.com/yK8xv4r.png)

**Comment by rougier** [comment]
Sorry, cannot see the liked picture (loading forever)

**Comment by RElbers** [comment]
I updated my previous message, I didn't know you could directly upload an image in github issues.

**Comment by rougier** [comment]
If the bug is only present on Windows, I suspect this is a window related problem. Can you try Adobe Reader (if it is installed, else I would not advise to install it) or Skim?

**Comment by RElbers** [comment]
Skim isn't on Windows as far as I can tell, but it renders correctly in Adobe reader.

![image](https://user-images.githubusercontent.com/13871379/146521782-cb4028fc-f246-417e-96da-3a98c2ee3182.png)

**Comment by rougier** [comment]
Ok, then I'm not sure I can easily fix it. Maybe it's worth to report the issue in matplotlib repo (and maybe it's already known).

**Comment by RElbers** [comment]
Seems like a hard bug to fix if it behaves differently in different PDF viewers. But looks like it's not something you can fix, so you can close this issue. Thanks for the nice book btw :)
