### ISSUE TITLE
Image licensing

### ISSUE THREAD

**Issue by m09** [rougier/scientific-visualization-book#44]
I'd like to start by deeply thanking you @rougier. This book is wonderful, and I thoroughly enjoyed reading it, as I enjoyed reading the NumPy book and investigating the NumPy exercises :)

To my question now: are the figures free to reuse in a commercial setting? I ask because the code of the figures seems to be (BSD) but the book is not (CC-BY-SA-NC). I ask because I'd like to include some of the book figures in some slides I have for a professional training session on matplotlib.

Thanks again for your great work and commitment to open source!

**Comment by rougier** [comment]
Thanks. the CC-BY-SA-NC is mainly to avoid people selling the book. So yes, you can use the figure in your slides.
