### ISSUE TITLE
Wrong Code in page 96 (Size, aspect & layout)?

### ISSUE THREAD

**Issue by zhangkaihua88** [rougier/scientific-visualization-book#53]
When I run the code `F`, `H` and `I`  scripts in Page 96 (Chapter 8 Size, aspect & layout), I got the figure as shown in the following figures. It is different from Figure 8.1. When I modify the axes aspect to 0.5, 1 and 2 respectively, it gets normal. It seems that  `aspect='auto'`  doesn't work.

- F, H and I
  <img width="295" alt="F script" src="https://user-images.githubusercontent.com/39882510/174038682-c45a16a8-5a21-4ec5-b2c6-2358fb59e9aa.png">
  <img width="291" alt="H script" src="https://user-images.githubusercontent.com/39882510/174038799-696424c4-88fa-4527-a2e6-114aba0ca5c9.png">
  <img width="290" alt="I script" src="https://user-images.githubusercontent.com/39882510/174038996-7cf45c48-2920-4ed7-81c7-e43ec7361380.png">

**Comment by rougier** [comment]
Do you run the code inside a notebook or from within terminal?

**Comment by zhangkaihua88** [comment]
I got same results in notebook and terminal.

**Comment by rougier** [comment]
I think you're right. Could you make a PR?
