### ISSUE TITLE
Link to antigrain.com is not working (Chapter 1, page 8)

### ISSUE THREAD

**Issue by labdmitriy** [rougier/scientific-visualization-book#57]
Hi @rougier,

I found that the link under "Anti‐Grain Geometry C++ library" to https://antigrain.com is not working, and it is confirmed in the description [here](https://github.com/ghaerr/agg-2.6), referring also to another site (http://agg.sourceforge.net/antigrain.com/):
> The official AGG site remains on Sourceforge, but doesn't see much activity. With [www.antigrain.com](http://www.antigrain.com/) recently inoperational, I thought a GitHub repo was in order, as the project demos stopped building with the site down.

Thank you.

**Comment by rougier** [comment]
Thanks. Could you make a PR?

**Comment by labdmitriy** [comment]
Hi @rougier,

Which link to use instead of https://antigrain.com/ - http://agg.sourceforge.net/antigrain.com/ or https://github.com/ghaerr/agg-2.6?

**Comment by rougier** [comment]
I think `http://agg.sourceforge.net/antigrain.com/ ` would be best.
