### ISSUE TITLE
Figure scope in Ruler's code (Chapter 1)

### ISSUE THREAD

**Issue by labdmitriy** [rougier/scientific-visualization-book#58]
Hi @rougier,

I found that you use global object `fig` in the Ruler object:
https://github.com/rougier/scientific-visualization-book/blob/a6e0607fa8dbcfa5e6251cd7b64b5a094ad4e0f9/code/anatomy/ruler.py#L24
And there are no errors in the code because global `fig` is created after function's definition.
Probably `self.fig` is more appropriate in this case?

Thank you.

**Comment by rougier** [comment]
Exactly, thank for the issue and the fix. Can you make a PR?
