### ISSUE TITLE
Inconsistent commas in the code (Chapter 2, page 22)

### ISSUE THREAD

**Issue by labdmitriy** [rougier/scientific-visualization-book#63]
Hi @rougier,

Еhere is a slight inconsistency in the code from the book - there is no comma after `zorder` argument, but after `linestyle` argument there is a comma (technically the latter case is not an error, but usually trailing comma is used with different code formatting):
```python
plt.plot(P[:,0], P[:,1], clip_on=False, zorder=-10
         color="k", linewidth=1.0, linestyle="--", )
```
Perhaps the following code was meant:
```python
plt.plot(P[:,0], P[:,1], clip_on=False, zorder=-10,
         color="k", linewidth=1.0, linestyle="--")
```

Thank you.

**Comment by rougier** [comment]
Nice catch, thanks. PR welcome.
