### ISSUE TITLE
Incorrect description and links to the code for Figures 2.3-2.5 (Chapter 2, pages 23-25)

### ISSUE THREAD

**Issue by labdmitriy** [rougier/scientific-visualization-book#64]
Hi @rougier,

The links to the code for Figures 2.3-2.5 have the name `coordinates/transform‐*.py` and URL https://github.com/rougier/scientific-visualization-book/blob/master/code/coordinates/transform-*.py, but the files have the name `transforms-*.py`, so probably the following will be correct:
Name - `coordinates/transforms‐*.py`
URL - https://github.com/rougier/scientific-visualization-book/blob/master/code/coordinates/transforms-*.py

Also for Figure 2.5 there is the same description as for Figure 2.3 (except for file name):

>Figure 2.3
>Axes boundaries in polar projection using a transform from normalized data co‐
ordinates to data coordinates (coordinates/transform‐polar.py).

>Figure 2.5
>Axes boundaries in polar projection using a transform from normalized data co‐
ordinates to data coordinates (coordinates/transform‐blend.py).

It seems that Figure 2.5 has incorrect description.

Thank you.

**Comment by rougier** [comment]
You're right, it's completely wrong. I think it was correct at some point, I need to track changes on commit.

**Comment by labdmitriy** [comment]
Hi @rougier, 

I found that there are 2 more links with `transform-*` names in `coordinates.rst` file:

>Axes boundaries in polar projection using a transform from normalized data coordinates to data coordinates ([:source:`coordinates/transform-polar.py`](https://github.com/rougier/scientific-visualization-book/blob/master/rst/coordinates.rst#id11)). label[`fig-transforms-polar`](https://github.com/rougier/scientific-visualization-book/blob/master/rst/coordinates.rst#id13)

> Using transforms to position precisely a text over a plot. Top panel uses normalized data coordinates (0.1,0.1), bottom panel uses normalized data coordinates (0.0,0.0) plus an offset (10,10) expressed in figure coordinates ([:source:`coordinates/transform-letter.py`](https://github.com/rougier/scientific-visualization-book/blob/master/rst/coordinates.rst#id19)). label[`fig-transforms-letter`](https://github.com/rougier/scientific-visualization-book/blob/master/rst/coordinates.rst#id21)

Is it correct?

Thank you.

**Comment by rougier** [comment]
I think I fixed them but maybe I forgot some. Best would be to rename transforms-* to transform-* in both text and filename.

**Comment by labdmitriy** [comment]
Hi @rougier,

It is not a problem to fix it, just to clarify (because before we renamed the links and names from `transform-*` to `transforms-*`) - do I understand correctly that I should rename all the links and names from `transforms-*` to `transform-*`, and also the corresponding files in the [folder](https://github.com/rougier/scientific-visualization-book/tree/master/code/coordinates) with code?

Thank you.

**Comment by rougier** [comment]
I think `transforms-*` is the right form and this the prefix for all the scripts now. Best is to only modify in the book but I think I've fixed them a few commits ago.
