### ISSUE TITLE
Code for Figure 2.6 from the book doesn't match the image (Chapter 2, pages 25-26)

### ISSUE THREAD

**Issue by labdmitriy** [rougier/scientific-visualization-book#66]
Hi @rougier,

The code in the book for `imshow()` function which is used for collage plotting is not consistent with the output image and the [Python file](https://github.com/rougier/scientific-visualization-book/blob/master/code/coordinates/collage.py).
In addition to the missing lines (which is probably done intentionally), for example `zorder` is used in the body but there is no argument with the same name (in Python file there is a such argument).
Could you please tell maybe it's all done that way on intentionally and it is not necessary to create issues like this and #64?

Thank you.

**Comment by labdmitriy** [comment]
> Yes, the idea was to show the main point, leaving out details. I think it can remain like this unless you tell me it's really confusing.

Ok, then I will remain it "as is" now.
Just as the point of view of the reader like me - it was a little confusing just once when I realize that the code from the book and supplemental files can differ, and after that I am just checking Python files anyway to verify my understanding and the code.
For #65 it was easier to fix because we added one line and got almost the same figure as we expect.
But here `zorder` is missing and seems like the code is not reproducible comparing to the fixed version #65.

So your decision will be final and I can help to implement the final decision.

**Comment by rougier** [comment]
I just added a precision.
