### ISSUE TITLE
"text positioning with transforms" example (figure 2.4) should perhaps normalize dx, dy by 72, not by fig.dpi

### ISSUE THREAD

**Issue by anntzer** [rougier/scientific-visualization-book#79]
The code for figure 2.4 is reproduced below for convenience:
```python
from matplotlib.transforms import ScaleTranslation

fig = plt.figure(figsize=(6, 4))

ax = fig.add_subplot(2, 1, 1)
plt.text(0.1, 0.1, "A", transform=ax.transAxes)

ax = fig.add_subplot(2, 1, 2)
dx, dy = 10/fig.dpi, 10/fig.dpi
offset = ScaledTranslation(dx, dy, fig.dpi_scale_trans)
plt.text(0, 0, "B", transform=ax.transAxes + offset)

plt.show()
```
I believe the scaling of dx, dy should be a division by 72, not by fig.dpi (more or less as you do in figure 2.5, in fact), as otherwise the appearance of the figure will depend on figure.dpi; e.g.
```python
from matplotlib import pyplot as plt, transforms as tr

size = 10

for dpi in [72, 300]:
    fig = plt.figure(dpi=dpi)

    ax = fig.add_subplot(2, 1, 1)
    dx = dy = size / fig.dpi
    offset = tr.ScaledTranslation(dx, dy, fig.dpi_scale_trans)
    ax.text(0, 0, "A", transform=ax.transAxes + offset, size=size)

    ax = fig.add_subplot(2, 1, 2)
    dx = dy = size / 72
    offset = tr.ScaledTranslation(dx, dy, fig.dpi_scale_trans)
    ax.text(0, 0, "A", transform=ax.transAxes + offset, size=size)

    fig.savefig(f"/tmp/test{dpi}.png")
    fig.savefig(f"/tmp/test{dpi}.pdf")
```
You can verify that here, the visual appearance of the top axis changes whereas the bottom one doesn't.

In a sense, this is redundant with figure 2.5; but perhaps division-by-72 should really be mentioned first and division-by-fig.dpi is more a side possibility?

**Comment by rougier** [comment]
You're right! Could you make a PR (for both book content and script)?

**Comment by anntzer** [comment]
Can I leave that to you? :)  Especially as I think (as noted above) there are some editorial decisions as to how to handle the redundancy with figure 2.5.

**Comment by rougier** [comment]
Sure. Note that it's not really redundant with figure 2.5 since in that case I use a blended transform to mix data/figue coordinate.

**Comment by anntzer** [comment]
Closed by 8d14fc2, afaict.  Thanks :)

**Comment by anntzer** [comment]
@rougier I recently realized that these examples can be implemented much more simply by using annotate(), which effectively provides a specialized version of ScaledTranslation; see https://github.com/matplotlib/matplotlib/pull/25905/files.
Clearly I think in the book the example with ScaledTranslation should stay at least for pedagogical purposes, but it's up to you whether you want to also mention the "easier" version with annotate().

**Comment by rougier** [comment]
Oh thanks for the ref, I did not think of it and I confirm it would be worth a mention in the text. Do you want to make a PR?

**Comment by anntzer** [comment]
I'd rather leave the word-smithing to you :)
